import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { getCurrentUser } from "@/lib/session";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/components/providers";
import { AuthProvider } from "@/contexts/auth-context";
import { Poppins } from "next/font/google";

const font = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Delta",
  description: "Generated by create delta",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("bg-background antialiased", font.variable)}>
        <AuthProvider initialUser={user}>
          <Providers>
            <Toaster />
            {children}
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
